### ISSUE TITLE
Add informations to a MergeRequest Item

### ISSUE THREAD

**Issue by TomBerriot** [TheGrowingPlant/gitlab-reviewer#15]
Missing valuable informations: 

* [x] Group Project / Project 
* [ ] Branch name
* [x] Have I voted State
* [x] CI State 

IMO the time spent since last update is not a very useful information

The `Group Project / Project` information could be shown in the title of a drop-down that would list MRs as suggested by https://github.com/TheGrowingPlant/gitlab-reviewer/issues/4

**Comment by notFloran** [comment]
> IMO the time spent since last update is not a very useful information

I use this information

**Comment by nclsHart** [comment]
I think there is no universal solution, everyone want different informations according to his own way to work.

As @TomBerriot have proposed, we could allow user to fully configure which columns to display in a drawer menu.

**Comment by notFloran** [comment]
The last pipeline is now in the response of https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr
