### ISSUE TITLE
Support emoji in MR title

### ISSUE THREAD

**Issue by nclsHart** [TheGrowingPlant/gitlab-reviewer#18]
Just an esthetic request for gitemoji practitioners.

Emoji are currently display as string in MR title :

![Screenshot_2019-04-23 GitLab Reviewer Dashboard](https://user-images.githubusercontent.com/833625/56610462-bcd30780-660f-11e9-92fa-27d2aea0aebe.png)

**Comment by notFloran** [comment]
Components :

* https://github.com/pladaria/react-emojione
* https://github.com/tommoor/react-emoji-render
