### ISSUE TITLE
Some merge requets are missing

### ISSUE THREAD

**Issue by notFloran** [TheGrowingPlant/gitlab-reviewer#23]
After some digging, the problem come from the the way you bundle project and merge request : for that you get "all" the projects but the api is paginated to 20 items so some projects are missing :)

**Comment by notFloran** [comment]
For MRCI we made a request per project : https://github.com/TheRedDot/MergeRequestsCI/blob/master/app/js/services/merge_request_fetcher.js#L30

**Comment by TomBerriot** [comment]
@notFloran Yes I saw how MRCI handled it and worried it would add more delay to the time it takes to refresh everything. I'm gonna switch for that
