### ISSUE TITLE
Name ?

### ISSUE THREAD

**Issue by notFloran** [TheGrowingPlant/gitlab-reviewer#3]

**Comment by notFloran** [comment]
Any idea @nclsHart  ?

**Comment by nclsHart** [comment]
Some new idea:

* ReviewLab
* GLower (GitLab + Tower)

And why not keeping gitlab-reviewer as a competitor.

**Comment by notFloran** [comment]
in the end we got used to gitlab-reviewer I propose to close the issue

**Comment by nclsHart** [comment]
I'm ok :+1:.

@TomBerriot?

**Comment by notFloran** [comment]
ping @TomBerriot

**Comment by TomBerriot** [comment]
I'm okay too 👌
